// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eglbygpbtkjgcsgtmazj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnbGJ5Z3BidGtqZ2NzZ3RtYXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjEwNzQsImV4cCI6MjA2NDAzNzA3NH0.UggocNkCArERVd0L27vEq2RRAZjKhE4rVL0LBSAmomo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});